### ISSUE TITLE
Developers: Bug Fix Priority List (alpha)

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#166]
After some brief voting on current and outstanding issues, we think we have reached a consensus that the following issues should receive the highest priority and in this order.

- [x] 1. *Open Cell ID Data* is not shown in DB viewer, thus blocking many other functions such as proper map view. #153 and [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/153#issuecomment-59853978) comment.

- [ ] 2. Fix *Map Viewer*, as described in issue #13, so that BTS/towers are color-coded as: 
>BLUE = currently connected BTS, 
>GREEN = other nearby BTS's. 
>RED = new or previously unknown BTS.

- [ ] 3. Since (1) and (2) are intimately related to "Detection-1: Changing LAC/CID": #91 .

- [x] 4. Remake the "About Menu" by adding buttons in: #132 .

Other suggestions are welcome.

**IFF** all these can be resolved for the next release, that release will be our **First Public BETA**!
IF **NOT** all can be resolved, the next working release will be another **Public ALPHA**.

**Comment by E3V3A** [comment]
@He3556  Can you please review this and give some feedback. AFAICT, # (2) has it's own issue and the rest seem fixed or outdated/non-relevant?

**Comment by He3556** [comment]
yes i agree, let's close it
